version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: dms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metadata_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Metadata Service
  metadata-service:
    build:
      context: ./metadata-service
      dockerfile: Dockerfile
    container_name: dms-metadata-service
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/metadata_db
      - MONGODB_URL=mongodb://mongodb:27017/
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./metadata-service:/app
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL...' &&
        sleep 5 &&
        echo 'Running migrations...' &&
        python -m app.migrations.create_user_project_tables &&
        echo 'Starting server...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # User Portal
  user-portal:
    build:
      context: ./user-portal
      dockerfile: Dockerfile.dev
    container_name: dms-user-portal
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./user-portal:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - metadata-service

volumes:
  postgres_data:
