version: '3.8'

x-common-environment:
  &default-env
  RABBITMQ_HOST: rabbitmq
  METADATA_SERVICE_URL: http://metadata-service:5002
  STORAGE_SERVICE_URL: http://storage-service:5003

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      <<: *default-env
      INGESTION_SERVICE_URL: http://ingestion-service:5001
      PROCESSING_SERVICE_URL: http://processing-service:5004
      SEARCH_SERVICE_URL: http://search-service:5005
      AI_SERVICE_URL: http://ai-service:5006
      NOTIFICATION_SERVICE_URL: http://notification-service:5007
      BULK_UPLOAD_SERVICE_URL: http://bulk-upload-service:5008
      SAGA_ORCHESTRATOR_URL: http://saga-orchestrator:5009
    depends_on:
      - ingestion-service
      - metadata-service
      - storage-service
      - processing-service
      - search-service
      - ai-service
      - notification-service
      - bulk-upload-service
      - saga-orchestrator
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion-service:
    build: ./ingestion-service
    ports:
      - "5001:5001"
    environment:
      <<: *default-env
    depends_on:
      - rabbitmq
    networks:
      - backend

  metadata-service:
    build: ./metadata-service
    ports:
      - "5002:5002"
    environment:
      <<: *default-env
      POSTGRES_HOST: postgres
      POSTGRES_DB: document_storage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      MONGO_HOST: mongo
      MONGO_DB: metadata_db
    depends_on:
      - postgres
      - mongo
    volumes:
      - ./metadata-service/config:/app/config
    networks:
      - backend

  storage-service:
    build: ./storage-service
    ports:
      - "5003:5003"
    environment:
      <<: *default-env
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: documents
    depends_on:
      - minio
    networks:
      - backend

  processing-service:
    build: ./processing-service
    ports:
      - "5004:5004"
    depends_on:
      - storage-service
    networks:
      - backend

  search-service:
    build: ./search-service
    ports:
      - "5005:5005"
    environment:
      ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - backend

  ai-service:
    build: ./ai-service
    ports:
      - "5006:5006"
    volumes:
      - ./ai-service:/app
    depends_on:
      - metadata-service
    networks:
      - backend

  notification-service:
    build: ./notification-service
    ports:
      - "5007:5007"
    environment:
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SMTP_USER: user
      SMTP_PASSWORD: password
    depends_on:
      - smtp
    networks:
      - backend

  bulk-upload-service:
    build: ./bulk-upload-service
    ports:
      - "5008:5008"
    environment:
      <<: *default-env
    depends_on:
      - metadata-service
      - storage-service
    networks:
      - backend

  saga-orchestrator:
    build: ./saga-orchestrator
    ports:
      - "5009:5009"
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - backend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: document_storage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d document_storage"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - backend

  smtp:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend

volumes:
  postgres_data:
  mongo_data:
  elasticsearch_data:
  rabbitmq_data:
  minio_data:

networks:
  backend:
    driver: bridge
