x-common-environment:
  &default-env
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: 5672
  RABBITMQ_USER: admin
  RABBITMQ_PASSWORD: password
  METADATA_SERVICE_URL: http://metadata-service:5002
  STORAGE_SERVICE_URL: http://storage-service:5003

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      <<: *default-env
      INGESTION_SERVICE_URL: http://ingestion-service:5001
      PROCESSING_SERVICE_URL: http://processing-service:5004
      SEARCH_SERVICE_URL: http://search-service:5005
      #AI_SERVICE_URL: http://ai-service:5006
      NOTIFICATION_SERVICE_URL: http://notification-service:5007
      BULK_UPLOAD_SERVICE_URL: http://bulk-upload-service:5008
      SAGA_ORCHESTRATOR_URL: http://saga-orchestrator:5009
    depends_on:
      ingestion-service:
        condition: service_healthy
      metadata-service:
        condition: service_healthy
      storage-service:
        condition: service_healthy
      processing-service:
        condition: service_healthy
      search-service:
        condition: service_healthy
      notification-service:
        condition: service_started
      bulk-upload-service:
        condition: service_started
      saga-orchestrator:
        condition: service_started
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion-service:
    build: ./ingestion-service
    ports:
      - "5001:5000"
    environment:
      <<: *default-env
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  metadata-service:
    build: ./metadata-service
    ports:
      - "5002:5002"
    environment:
      <<: *default-env
      POSTGRES_HOST: postgres
      POSTGRES_DB: document_storage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      MONGO_HOST: mongo
      MONGO_DB: metadata_db
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5002/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./metadata-service/config:/app/config
    networks:
      - backend

  storage-service:
    build: ./storage-service
    ports:
      - "5003:5003"
    environment:
      <<: *default-env
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: documents
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  processing-service:
    build: ./processing-service
    ports:
      - "5004:5004"
    depends_on:
      - storage-service
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5004/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  search-service:
    build: ./search-service
    ports:
      - "5005:5005"
    environment:
      <<: *default-env
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_PROTOCOL: http
    depends_on:
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5005/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    container_name: graylog-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "bootstrap.memory_lock=true"
      - "action.destructive_requires_name=false"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 120s
    networks:
      - graylog
      - backend

  ai-service:
    build: ./ai-service
    ports:
      - "5006:5006"
    volumes:
      - ./ai-service:/app
    depends_on:
      - metadata-service
    networks:
      - backend

  notification-service:
    build: ./notification-service
    ports:
      - "5007:5007"
    environment:
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SMTP_USER: user
      SMTP_PASSWORD: password
    depends_on:
      - smtp
    networks:
      - backend

  bulk-upload-service:
    build: ./bulk-upload-service
    ports:
      - "5008:5008"
    environment:
      <<: *default-env
    depends_on:
      - metadata-service
      - storage-service
    networks:
      - backend

  saga-orchestrator:
    build: ./saga-orchestrator
    ports:
      - "5009:5009"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASSWORD: password
      RABBITMQ_VHOST: /
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5009/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  # Logging services
  graylog:
    image: graylog/graylog:5.2
    container_name: graylog
    restart: always
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://admin:password@mongo:27017/graylog?authSource=admin
    ports:
      - 9002:9000
      - 12201:12201
      - 12201:12201/udp
    depends_on:
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - graylog
      - backend

  smtp:
    image: mailhog/mailhog:latest
    container_name: smtp
    hostname: smtp
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - backend

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - backend
      - graylog

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: document_storage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d document_storage"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - backend

  user-portal:
    build:
      context: ./user-portal
      dockerfile: Dockerfile.dev
    container_name: dms-user-portal
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./user-portal:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - metadata-service

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dms.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - backend

networks:
  graylog:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  elasticsearch_data:
  rabbitmq_data:
  minio_data:
  pgadmin_data:
