version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads  # Persist uploaded files
      - ./instance:/app/instance  # Persist SQLite database
    environment:
      - FLASK_ENV=production
    depends_on:
      - tesseract
    networks:
      - app-network

  tesseract:
    image: tesseractshadow/tesseract4re
    networks:
      - app-network

networks:
  app-network:
    driver: bridge