# Dockerfile.postgres
FROM postgres:13

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=metadata_db

# Expose PostgreSQL port
EXPOSE 5432